---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
```

```{r}
stackoverflow <- read_csv("data/stackoverflow.csv") %>% 
  janitor::clean_names()

stackoverflow_tidied <- stackoverflow %>% 
  mutate(remote = fct_relevel(remote, c("Remote", "Not remote"))) %>% 
  select(-respondent)

stacko
```

# Overview
```{r}
glimpse(stackoverflow)
```

## Get a feeling with variables
```{r}
stackoverflow_tidied %>% 
  count(remote, sort = TRUE)

stackoverflow_tidied %>% 
  count(country, sort = TRUE)

stackoverflow_tidied %>% 
  count(years_coded_job, sort = TRUE) %>% 
  ggplot(aes(years_coded_job, n )) + 
  geom_col()
```

## Visualisation with something interested
```{r}
stackoverflow_tidied %>% 
  ggplot(aes(remote, years_coded_job)) + 
  geom_boxplot() + 
  labs(
    x = "",
    y = "Years of coding experience"
  )
```

# Build a simple classifcation model 

```{r}
library(broom)
stackoverflow_tidied %>%
  glm(remote ~ ., data = ., family = "binomial") %>% 
  broom::tidy()
```

## Deal with imbalance data 

Upsampling or oversampling. Add more of the minority class


```{r}
library(rsample)

set.seed(1234)

stack_split <- stackoverflow_tidied %>% 
  initial_split(0.8, stata = "remote")

stack_train <- training(stack_split)
stack_test <- testing(stack_split)

```

### Upsampling 

```{r}
library(caret)
up_train <- upSample(
  x = select(stack_train, -remote),
  y = stack_train$remote,
  yname = "remote" ) %>% 
  as_tibble()

up_train %>% 
  count(remote)
```

# Training models 

```{r}
stack_glm <- train(remote ~ ., method = "glm", family = "binomial", 
                   data = stack_train, 
                   trControl = trainControl(method = "boot",
                                            sampling = "up"))

stack_glm
```


```{r}
stack_rf <- train(remote ~ ., method = "rf", 
                  data = stack_train,
                  trControl = trainControl(method = "boot",
                                           sampling = "up"))
```

### Confustion Matrix

```{r}
library(yardstick)
stack_test %>% 
  mutate(logistic_regression = predict(stack_glm, stack_test)) %>% 
  conf_mat(truth = remote, estimate = logistic_regression)
```

```{r}
stack_test %>% 
  mutate(random_forrest = predict(stack_rf, stack_test)) %>% 
  conf_mat(truth = remote, estimate = random_forrest)
```

### Testing Results 

```{r}
testing_results <- stack_test %>% 
  mutate(logistic_regression = predict(stack_glm, stack_test),
         random_forrest = predict(stack_rf, stack_test))
```


```{r}
# accuracy
accuracy(testing_results,truth = remote, estimate = logistic_regression)
accuracy(testing_results,truth = remote, estimate = random_forrest)
```

```{r}
## Positive predict value
ppv(testing_results, truth = remote, estimate = logistic_regression)
ppv(testing_results, truth = remote, estimate = random_forrest)
```

