---
title: "Untitled"
author: "Thinh"
date: "6/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(caret)
library(rsample)
```

```{r}
data <- read_csv("~/Downloads/xgboost_pa.csv") %>% 
  mutate(aha_check = as_factor(aha_check))

set.seed(1234)

data_split <- data %>% 
  initial_split(prop = .8)

data_training <- training(data_split)
data_testing <- testing(data_split)

```

```{r}
xgb_model <- train(aha_check ~ ., method = "xgbTree", data = data_training)


logit_model <- train(aha_check ~ ., method = "glm", family = "binomial", data = data_training)
```


```{r}
modeling_results_testing <- data_testing %>% 
  mutate(XGB = predict(xgb_model,data_testing)) %>% 
  mutate(LOGIT = predict(logit_model, data_testing))


write_csv(modeling_results_testing, "~/Downloads/xgboost_result.csv")
```

```{r}
library(yardstick)
# ...xgboost model
metrics(modeling_results_testing, truth = aha_check, estimate = XGB)
metrics(modeling_results_testing, truth = aha_check, estimate = LOGIT)

```


```{r}
modeling_results_testing %>% 
  mutate(logit_model = predict(logit_model, data_testing)) %>% 
  conf_mat(truth = aha_check, estimate = logit_model)
```

