---
title: "Statistical Learning"
output: html_notebook
---

### Presiquisite
```{r}
library(tidyverse)
theme_set(theme_light())
```

# Adveristing data 

## What is the relationship between budget of channel and sales ?

```{r}
adversiting <- read_csv("~/Documents/GitHub/myr/ISLR/ISLR-Auto/Advertising.csv")

adversiting <- adversiting %>% 
  select(-X1)

advertising_tided <- adversiting %>% 
  gather(channel, budget, -Sales)

names(advertising_tided) <- rattle::normVarNames(set_names(names(advertising_tided)))

advertising_tided %>% 
  ggplot(aes(budget, sales)) + 
  geom_point() + 
  facet_wrap(~ channel, scales = "free") + 
  scale_y_continuous(breaks = c(5,10,15,20,25))
```

Fit the simple linear regression to the plot

### Modelr Approach

```{r}
library(modelr)
channel_model <- function(df) {
 lm(sales ~ budget, data = df)
}

prediction <- advertising_tided %>% 
  group_by(channel) %>% 
  nest() %>% 
  mutate(
    model = map(data, channel_model),
    resid = map2(data, model, add_residuals),
    pred = map2(data, model, add_predictions)
  ) %>% 
  unnest(pred)
```


``` {r}
advertising_tided %>% 
  ggplot(aes(budget, sales)) + 
  geom_point() + 
  geom_line(data = prediction, aes(y = pred), colour = "red") + 
  facet_wrap(~ channel, scales = "free") + 
  scale_y_continuous(breaks = seq(5, 25, 5)) + 
  scale_x_continuous(labels = scales::dollar_format()) +
  labs(
    x = "Budget (thousounds of dollar)",
    y = "Sales (thousands of units)",
    title = "Sales in 200 different markets with budget spending on media"
  )
  
```

### ggplot approach


```{r}
advertising_tided %>% 
  ggplot(aes(budget, sales)) + 
  geom_point() + 
  geom_smooth(method = "lm", se = FALSE) +
  facet_wrap(~ channel, scales = "free") + 
  scale_y_continuous(breaks = seq(5, 25, 5)) + 
  scale_x_continuous(labels = scales::dollar_format()) +
  labs(
    x = "Budget (thousounds of dollar)",
    y = "Sales (thousands of units)",
    title = "Sales in 200 different markets with budget spending on media"
  )
```


# Income data 


```{r}
income1 <- read_csv("~/Documents/GitHub/myr/ISLR/ISLR-Auto/Income1.csv")
income2 <- read_csv("~/Documents/GitHub/myr/ISLR/ISLR-Auto/Income2.csv")

income1 <- income %>% 
  select(-X1)
income2 <- income2 %>% 
  select(-X1)


names(income1) <- set_names(rattle::normVarNames(names(income1)))
names(income2) <- set_names(rattle::normVarNames(names(income2)))
```

```{r}
mod <- loess(income ~ education, data = income1)

income1 <- income1 %>% 
  add_predictions(mod)
```

```{r}
income1 %>% 
  ggplot(aes(education, income)) +
  geom_point(colour = "red") +
  geom_segment(aes(xend = education, yend = pred)) + 
  geom_smooth(se = FALSE)
```


