---
title: "French Trains"
author: "Thinh"
date: "6/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
theme_set(theme_light())

full_trains <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-02-26/full_trains.csv")
```


```{r}
full_trains %>% 
  count(year, month)
  count(departure_station, arrival_station)
  
november_2018 <- full_trains %>% 
  filter(year == 2018, month == 11) %>% 
  mutate(pct_late_at_departure = num_late_at_departure/total_num_trips,
         departure_station = str_to_title(departure_station))


november_2018 %>% 
  ggplot(aes(pct_late_at_departure)) + 
  geom_histogram(binwidth = 0.05) + 
  scale_x_continuous(labels = scales::percent_format())

november_2018 %>% 
  mutate(departure_station = fct_lump(departure_station, 3)) %>% 
  ggplot(aes(departure_station, pct_late_at_departure)) + 
  geom_boxplot() + 
  scale_y_continuous(labels = scales::percent_format())
  
```

