---
title: "Wine Ratings"
author: "Thinh"
date: "6/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidytuesdayR)
library(tidyverse)
theme_set(theme_light())

tidytuesday <- tt_load("2019-05-28")

wine_ratings <- tidytuesday$`winemag-data-130k-v2` %>% 
  select(-X1) %>% 
  mutate(year = as.integer(str_extract(title, "(20\\d\\d)")))
```

```{r}
skimr::skim(wine_ratings)
```


```{r}
wine_ratings %>% 
  count(country, sort = TRUE)

wine_ratings %>% 
  count(designation, sort = TRUE)

wine_ratings %>% 
  count(country, region_1, sort = TRUE)

wine_ratings %>% 
  count(variety, sort = TRUE)

wine_ratings %>% 
  ggplot(aes(year)) + 
  geom_histogram()

wine_ratings %>% 
  ggplot(aes(points)) + 
  geom_histogram(binwidth = 1)

wine_ratings %>% 
  ggplot(aes(price)) +
  geom_histogram() + 
  scale_x_log10()
```


```{r}
ggplot(wine_ratings, aes(price, points)) +
  geom_point(alpha = .1) + 
  geom_smooth(method = "lm")  +
  scale_x_log10() 

summary(lm(points ~ log2(price), wine_ratings))
```

Everytime the price doubles, the expected number of points goes up by 2.


```{r}
model <- wine_ratings %>%
  replace_na(list(taster_name = "Missing")) %>% 
  mutate(country = fct_relevel(fct_lump(country, 7), "US"),
         taste_name = fct_relevel(fct_lump(taster_name, 6), "Missing"))  %>% 
  lm(points ~ log2(price) + country + year + taster_name, data = .  )


model %>% 
  broom::tidy(conf.int = TRUE) %>% 
  filter(term != "Intercept") %>% 
  mutate(term = str_replace(term, "country", "Country: "),
         term = str_replace(term, "taster_name", "Taster: "),
         term = fct_reorder(term, estimate)) %>% 
  ggplot(aes(estimate, term)) + 
  geom_point() + 
  geom_errorbar(aes(xmin = conf.low, xmax = conf.high))
```

